---
title: "hw3_nn2477"
author: "Nhu Nguyen"
date: "2023-10-11"
output: github_document
---
## problem 1
## loading necessary libraries 
```{r}
library(tidyverse)
library(ggplot2)
library(p8105.datasets)
data("instacart")
```

## getting the number of unique aisles
```{r}
instacart %>% 
  summarise(count = n_distinct(aisle))
```

## getting the aisles with the most item ordered
```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarise(total_items = n()) %>% 
  arrange(desc(total_items))
```

## making plot for aisle and number of items ordered 

```{r}
instacart %>% 
  group_by(aisle) %>% 
  summarise(total_items = n()) %>% 
  filter(total_items > 10000) %>% 
  arrange(desc(total_items)) %>% 
ggplot(aes(x = reorder(aisle, -total_items), y = total_items)) +
  geom_bar(stat = "identity", fill = "skyblue") + 
  labs (
    title = "number of items ordered in each aisle", 
    x = "aisle",
    y = "total items ordered"
  ) + 
  coord_flip() + 
  theme_minimal()
```

## making a table for the three most popular items 

```{r}
instacart %>% 
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>% 
  group_by(aisle, product_name) %>% 
  summarise(order_count = n()) %>% 
  arrange(aisle, desc(order_count)) %>% 
  group_by(aisle) %>% 
  slice_max(order_count, n = 3) %>% 
  pivot_wider(
    names_from = aisle,
    values_from = order_count)
```

## create table for pink landy apples and coffee ice cream 
```{r}
instacart %>% 
  mutate(order_dow = recode(
    order_dow,
    "0" = "sunday",
    "1" = "monday",
    "2" = "tuesday",
    "3" = "wednesday",
    "4" = "thursday",
    "5" = "friday",
    "6" = "saturday")) %>% 
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  group_by(order_dow, product_name) %>% 
  summarise(mean_hour = mean(order_hour_of_day, na.rm = TRUE)) 
```

## problem 2 
loading dataset 
```{r}
data("brfss_smart2010")
```

## cleaning dataset 

```{r}
brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  separate(locationdesc, into = c("state", "county")) %>% 
  filter(topic == "Overall Health",
     response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = factor(
    response,
    levels = c("Poor", "Fair", "Good", "Very good", "Excellent"), exclude = NULL)) %>% 
  rename("general health" = response) %>% 
  select(-locationabbr, -class, -question, -data_value_type, -data_value_footnote_symbol, -data_value_footnote, -data_source, -class_id, -topic_id, -location_id, -question_id) %>% 
  pivot_longer()


```


```{r}
janitor::clean_names() %>% 
  separate(locationdesc, into = c("state", "county")) %>% 
  select(-locationabbr, -question, -class, -question_id, -class_id, -topic_id, -data_value_type, -location_id, -data_value_footnote, -data_value_footnote_symbol) %>% 
  filter(topic == "overall health", 
         response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  mutate(response = factor(
    response, 
     levels = c("Poor", "Fair", "Good", "Very good", "Excellent"), exclude = NULL)) %>% 
  rename("General Health" = response)

 
```

